</div> <!-- container-fluid -->
</div>
<!-- End Page-content -->

<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                2023 © FBB.
            </div>
            <div class="col-sm-6">
                <div class="text-sm-right d-none d-sm-block">
                    Desenvolvido por Fundação Banco do Brasil
                </div>
            </div>
        </div>
    </div>
</footer>

</div>
<!-- end main content-->

</div>
<!-- END layout-wrapper -->

<!-- Overlay-->
<div class="menu-overlay"></div>

<!-- jQuery  -->
<script src="<?= HOME_URI . "assets/js/jquery.min.js" ?>"></script>
<script src="<?= HOME_URI . "assets/js/bootstrap.bundle.min.js"?>"></script>
<script src="<?= HOME_URI . "assets/js/metismenu.min.js" ?>"></script>
<script src="<?= HOME_URI . "assets/js/waves.js" ?>"></script>
<script src="<?= HOME_URI . "assets/js/simplebar.min.js" ?>"></script>

<!-- Morris Js-->
<script src="<?= HOME_URI . "vendor/morris-js/morris.min.js" ?>"></script>
<!-- Raphael Js-->
<script src="<?= HOME_URI . "vendor/raphael/raphael.min.js" ?>"></script>

<!-- Morris Custom Js-->
<script src="<?= HOME_URI . "assets/pages/dashboard-demo.js" ?>"></script>

<!-- App js -->
<script src="<?= HOME_URI . "assets/js/theme.js" ?>"></script>

<script type="text/javascript"
        src="<?= HOME_URI . "vendor/jquery-validation-1.16.0/dist/jquery.validate.min.js" ?>"></script>
<script type="text/javascript" src="<?= HOME_URI . "vendor/jquery-mask-plugin/dist/jquery.mask.min.js" ?>"></script>
<script type="text/javascript" src="<?= HOME_URI . "vendor/chosen_v1.8.7/chosen.jquery.js" ?>"></script>

<!-- DataTables js -->
<script type="text/javascript" src="<?= HOME_URI . "vendor/datatables/datatables.min.js" ?>"></script>
<script type="text/javascript" language="javascript" src="<?= HOME_URI . "vendor/datatables/moment.min.js" ?>"></script>
<script type="text/javascript" language="javascript"
        src="<?= HOME_URI . "vendor/datatables/datetime-moment.js" ?>"></script>

<!-- Global js -->
<script type="text/javascript" src="<?= HOME_URI . "assets/js/global.js" ?>"></script>